name: Deploy to Shared Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: FTP Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.ftp.papermuglab.com }}
          username: ${{ secrets.papermug }}
          password: ${{ secrets.5PHa$2@0$u }}
          server-dir: ${{ secrets./public_html/ }}
          protocol: ftps
          port: 21
