name: Deploy to Paper Mug Lab

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Shared Hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: papermuglab.com
          username: "papermug"
          password: "5PHa$2@0$u"
          protocol: ftps
          port: 21
          server-dir: /public_html/
